name: Deploy Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: |
          echo "Running website tests..."
          test -f index.html
          test -f style.css
          test -f script.js
          echo "Tests passed!"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://js-devops-vijay-2026 \
            --exclude ".git/*" \
            --exclude ".github/*"

      - name: Deployment successful
        run: echo "Website deployed successfully to S3!"